- name: Ensure .zshrc file exists
  file:
    path: "{{ zshrc_file }}"
    state: touch
    mode: '0644'

- name: Set custom environment variables in .zshrc
  blockinfile:
    path: "{{ zshrc_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: CUSTOM ENV VARS"
    block: |
      {% for var in custom_env_vars %}
      export {{ var.name }}="{{ var.value }}"
      {% endfor %}
