- name: Run provision code generation
  shell: |
    cd {{ go_sky_path }}/provision
    source {{ zsh_file }}
    make gen
  register: provision_codegen_result
  ignore_errors: true

- name: Show provision codegen stdout
  debug:
    var: provision_codegen_result.stdout_lines

- name: Show provision codegen stderr (if any)
  debug:
    var: provision_codegen_result.stderr_lines
  when: provision_codegen_result.rc != 0

- name: Run proto code generation
  shell: |
    cd {{ go_sky_path }}/proto
    source {{ zsh_file }}
    make gen
  register: proto_codegen_result
  ignore_errors: true

- name: Show proto codegen stdout
  debug:
    var: proto_codegen_result.stdout_lines

- name: Show proto codegen stderr (if any)
  debug:
    var: proto_codegen_result.stderr_lines
  when: proto_codegen_result.rc != 0

- name: Run full project generation including GraphQL
  shell: |
    cd {{ go_sky_path }}
    source {{ zsh_file }}
    make gen
  register: full_codegen_result
  ignore_errors: true

- name: Run go mod tidy
  shell: |
    cd {{ go_sky_path }}
    source {{ zsh_file }}
    go mod tidy

- name: Show full project codegen stdout
  debug:
    var: full_codegen_result.stdout_lines

- name: Show full project codegen stderr (if any)
  debug:
    var: full_codegen_result.stderr_lines
  when: full_codegen_result.rc != 0
