- name: Run provision code generation
  shell: zsh -l -c 'cd {{ go_sky_path }}/provision && make gen'
  register: provision_codegen_result
  ignore_errors: true

- name: Show provision codegen stdout
  debug:
    var: provision_codegen_result.stdout_lines

- name: Show provision codegen stderr (if any)
  debug:
    var: provision_codegen_result.stderr_lines
  when: provision_codegen_result.rc != 0

- name: Run proto code generation
  shell: zsh -l -c 'cd {{ go_sky_path }}/proto && make gen'
  register: proto_codegen_result
  ignore_errors: true

- name: Show proto codegen stdout
  debug:
    var: proto_codegen_result.stdout_lines

- name: Show proto codegen stderr (if any)
  debug:
    var: proto_codegen_result.stderr_lines
  when: proto_codegen_result.rc != 0

- name: Run full project generation including GraphQL
  shell: zsh -l -c 'cd {{ go_sky_path }} && make gen'
  register: full_codegen_result
  ignore_errors: true

- name: Run go mod tidy
  shell: zsh -l -c 'cd {{ go_sky_path }} && go mod tidy'

- name: Show full project codegen stdout
  debug:
    var: full_codegen_result.stdout_lines

- name: Show full project codegen stderr (if any)
  debug:
    var: full_codegen_result.stderr_lines
  when: full_codegen_result.rc != 0
