- name: Ensure ~/.ssh directory exists
  file:
    path: "{{ ssh_key_path | dirname }}"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: false

- name: Generate SSH keypair
  openssh_keypair:
    path: "{{ ssh_key_path }}"
    type: ed25519
    comment: "{{ ssh_key_comment }}"
    force: false
