- name: Setup Development Environment For SkyPlan Project
  hosts: local
  gather_facts: true

  tasks:
    - name: Setup ZSH
      include_role:
        name: zsh
    - name: Setup SSH For Git and Github
      include_role:
        name: ssh_setup
    - name: Clone SkyHop Repos
      include_role:
        name: download_repos
    - name: Install Node.js
      include_role:
        name: download_node
    - name: Setup dev environment
      include_role:
        name: portal_spa_setup
    - name: Setup local hosts
      include_role:
        name: update_hosts
    - name: Install Go 1.20.14
      include_role:
        name: download_golang
