---
- name: Set Go project path
  set_fact:
    go_project_path: "{{ ansible_env.HOME }}/work/go-sky"

- name: Ensure go.mod exists in project path
  stat:
    path: "{{ go_project_path }}/go.mod"
  register: gomod_check

- name: Fail if go.mod is not found (repo may not be cloned)
  fail:
    msg: "go.mod not found at {{ go_project_path }}. Ensure the go-sky repo is cloned first."
  when: not gomod_check.stat.exists

- name: Install Go tools using 'go install'
  shell: |
    go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.19.0
    go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.20.0
    go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.32.0
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0
    go install github.com/cosmtrek/air@v1.42.0
    # These are the latest versions of gopls, dlv, and staticcheck which work with Go 1.20.
    # Update these to @latest once the product has moved to a supported version of Go.
    go install golang.org/x/tools/gopls@v0.15.3
    go install github.com/go-delve/delve/cmd/dlv@v1.22.1
    go install honnef.co/go/tools/cmd/staticcheck@v0.4.7
  args:
    chdir: "{{ go_project_path }}"
    executable: /bin/zsh

- name: Install json2tmux via go get
  shell: go get github.com/ericksonjoseph/json2tmux
  args:
    chdir: "{{ go_project_path }}"
    executable: /bin/zsh

- name: Install json2tmux binary
  shell: go install github.com/ericksonjoseph/json2tmux
  args:
    chdir: "{{ go_project_path }}"
    executable: /bin/zsh
