---
- name: Ensure curl and tar are installed (macOS only)
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - gnu-tar
  when: ansible_facts['os_family'] == 'Darwin'

- name: Set Go download architecture
  set_fact:
    go_arch: "{{ 'arm64' if ansible_facts['architecture'] == 'arm64' else 'amd64' }}"
  when: ansible_facts['os_family'] == 'Darwin'

- name: Remove existing Go installation if any
  file:
    path: /usr/local/go
    state: absent
  become: true
  when: ansible_facts['os_family'] == 'Darwin'

- name: Download Go 1.20.14 archive for macOS
  get_url:
    url: "https://go.dev/dl/go1.20.14.darwin-{{ go_arch }}.tar.gz"
    dest: /tmp/go1.20.14.tar.gz
    mode: "0644"
    validate_certs: no # <-- disables certificate validation
  when: ansible_facts['os_family'] == 'Darwin'

- name: Extract Go to /usr/local
  unarchive:
    src: /tmp/go1.20.14.tar.gz
    dest: /usr/local
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: true
  when: ansible_facts['os_family'] == 'Darwin'

- name: Ensure Go binary path is added to .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="$PATH:/usr/local/go/bin"'
    insertafter: EOF
    state: present

- name: Verify Go installation
  shell: |
    source "{{ ansible_env.HOME }}/.zshrc"
    go version
  args:
    executable: /bin/zsh
  register: go_version_check

- name: Show installed Go version
  debug:
    var: go_version_check.stdout
