---
- name: Ensure Homebrew is installed
  stat:
    path: "{{ item }}"
  loop:
    - /opt/homebrew/bin/brew
    - /usr/local/bin/brew
  register: homebrew_paths
  when: ansible_facts['os_family'] == 'Darwin'

- name: Set Homebrew installed flag
  set_fact:
    homebrew_installed: "{{ homebrew_paths.results | selectattr('stat.exists', 'equalto', true) | list | length > 0 }}"
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Homebrew if not installed
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    executable: /bin/zsh
  when:
    - ansible_facts['os_family'] == 'Darwin'
    - not homebrew_installed

# Visual Studio Code
- name: Check if Visual Studio Code is installed
  stat:
    path: /Applications/Visual Studio Code.app
  register: vscode_stat
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Visual Studio Code via brew cask
  command: brew install --cask visual-studio-code
  register: vscode_install
  failed_when: vscode_install.rc != 0 and "'already an App' not in vscode_install.stderr"
  changed_when: vscode_install.rc == 0
  when:
    - ansible_facts['os_family'] == 'Darwin'
    - not vscode_stat.stat.exists

# Sequel Ace
- name: Check if Sequel Ace is installed
  stat:
    path: /Applications/Sequel Ace.app
  register: sequel_ace_stat
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Sequel Ace via brew cask
  command: brew install --cask sequel-ace
  register: sequel_ace_install
  failed_when: sequel_ace_install.rc != 0 and "'already an App' not in sequel_ace_install.stderr"
  changed_when: sequel_ace_install.rc == 0
  when:
    - ansible_facts['os_family'] == 'Darwin'
    - not sequel_ace_stat.stat.exists

# MySQL (CLI tool, no .app)
- name: Check if MySQL is installed
  command: brew list mysql
  register: mysql_check
  failed_when: false
  changed_when: false
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install MySQL
  homebrew:
    name: mysql
    state: present
  when:
    - ansible_facts['os_family'] == 'Darwin'
    - mysql_check.rc != 0

# Tmux (CLI tool)
- name: Check if Tmux is installed
  command: brew list tmux
  register: tmux_check
  failed_when: false
  changed_when: false
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Tmux
  homebrew:
    name: tmux
    state: present
  when:
    - ansible_facts['os_family'] == 'Darwin'
    - tmux_check.rc != 0

# CTOP (CLI TOOL)
- name: Check if CTOP is installed
  command: brew list ctop
  register: ctop_check
  failed_when: false
  changed_when: false
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install CTOP
  homebrew:
    name: ctop
    state: present
  when:
    - ansible_facts['os_family'] == 'Darwin'
    - ctop_check.rc != 0